# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 22:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180116_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='voters',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
